steps:
  # 1. Build the Docker image (will use your Go Dockerfile)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_ARTIFACT_REGISTRY_PATH}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '-t'
      - '${_ARTIFACT_REGISTRY_PATH}/${_IMAGE_NAME}:latest'
      - '.' # Assumes Dockerfile is in the root
    id: 'Build Docker Image'

  # 2. Push the 'commit-sha' tagged image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_ARTIFACT_REGISTRY_PATH}/${_IMAGE_NAME}:$COMMIT_SHA']
    id: 'Push Specific Tag to Artifact Registry'

  # 3. Push the 'latest' tagged image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_ARTIFACT_REGISTRY_PATH}/${_IMAGE_NAME}:latest']
    id: 'Push Latest Tag to Artifact Registry'

  # 4. Dynamically update the image in the Kubernetes Deployment manifest
  # This replaces the placeholder image with the exact image built in this pipeline.
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Updating k8s/deployment.yaml with image: ${_ARTIFACT_REGISTRY_PATH}/${_IMAGE_NAME}:${COMMIT_SHA}"
        # --- UPDATED SED COMMAND TO MATCH NEW PLACEHOLDER ---
        sed -i "s|image: __IMAGE_PLACEHOLDER__|image: ${_ARTIFACT_REGISTRY_PATH}/${_IMAGE_NAME}:${COMMIT_SHA}|g" k8s/deployment.yaml
        # --- END OF UPDATED SED COMMAND ---
    id: 'Update Image in Deployment Manifest'


  # 5. Deploy to GKE using kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/' # Applies all YAML files in the k8s/ directory
      # - '--namespace=${_K8S_NAMESPACE}' # Uncomment if deploying to a specific namespace
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_GKE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER_NAME}'
      - 'CLOUDSDK_CORE_PROJECT=${PROJECT_ID}' # PROJECT_ID is a built-in substitution from Cloud Build
    id: 'Deploy to GKE'

images:
  - '${_ARTIFACT_REGISTRY_PATH}/${_IMAGE_NAME}:$COMMIT_SHA'
  - '${_ARTIFACT_REGISTRY_PATH}/${_IMAGE_NAME}:latest'

substitutions:
  _ARTIFACT_REGISTRY_PATH: 'us-central1-docker.pkg.dev/cnap-demo/tasky-app-repo-44519986' # <--- UPDATED with your actual output
  _IMAGE_NAME: 'tasky'
  _GKE_CLUSTER_NAME: 'tasky-app-cluster-44519986' # <--- IMPORTANT: You need to get this from your full `terraform output gke_cluster_name`
  _GKE_ZONE: 'us-central1-a'               # <--- IMPORTANT: You need to get this from your full `terraform output gke_cluster_endpoint` (for the zone) or `var.zone`
  _K8S_NAMESPACE: 'tasky-ns'            # Optional: uncomment if using a specific namespace


options:
  logging: CLOUD_LOGGING_ONLY
