steps:
  # 1. Build the Docker image (will use your Go Dockerfile)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_ARTIFACT_REGISTRY_PATH}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '-t'
      - '${_ARTIFACT_REGISTRY_PATH}/${_IMAGE_NAME}:latest'
      - '.' # Assumes Dockerfile is in the root
    id: 'Build Docker Image'

  # 2. Push the 'commit-sha' tagged image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_ARTIFACT_REGISTRY_PATH}/${_IMAGE_NAME}:$COMMIT_SHA']
    id: 'Push Specific Tag to Artifact Registry'

  # 3. Push the 'latest' tagged image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_ARTIFACT_REGISTRY_PATH}/${_IMAGE_NAME}:latest']
    id: 'Push Latest Tag to Artifact Registry'

  # 4. Dynamically update the image in the Kubernetes Deployment manifest
  # This replaces the placeholder image with the exact image built in this pipeline.
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Updating k8s/deployment.yaml with image: ${_ARTIFACT_REGISTRY_PATH}/${_IMAGE_NAME}:${COMMIT_SHA}"
        # Ensure this sed command exactly matches the placeholder in your k8s/deployment.yaml
        sed -i "s|image: YOUR_ARTIFACT_REGISTRY_PATH/tasky:placeholder|image: ${_ARTIFACT_REGISTRY_PATH}/${_IMAGE_NAME}:${COMMIT_SHA}|g" k8s/deployment.yaml
    id: 'Update Image in Deployment Manifest'

  # 5. Deploy to GKE using kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/' # Applies all YAML files in the k8s/ directory
      # - '--namespace=${_K8S_NAMESPACE}' # Uncomment if deploying to a specific namespace
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_GKE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER_NAME}'
      - 'CLOUDSDK_CORE_PROJECT=${PROJECT_ID}' # PROJECT_ID is a built-in substitution from Cloud Build
    id: 'Deploy to GKE'

images:
  - '${_ARTIFACT_REGISTRY_PATH}/${_IMAGE_NAME}:$COMMIT_SHA'
  - '${_ARTIFACT_REGISTRY_PATH}/${_IMAGE_NAME}:latest'

substitutions:
  _ARTIFACT_REGISTRY_PATH: 'us-central1-docker.pkg.dev/your-project-id/your-repo-id' # REPLACE
  _IMAGE_NAME: 'tasky'
  _GKE_CLUSTER_NAME: 'your-gke-cluster-name' # REPLACE
  _GKE_ZONE: 'us-central1-a'               # REPLACE
  # _K8S_NAMESPACE: 'tasky-ns'            # Optional: uncomment if using a specific namespace

options:
  logging: CLOUD_LOGGING_ONLY
